FROM composer/composer

MAINTAINER Will Hall "will@willhallonline.co.uk"

# Install PHPCS and Drupal Coding Standards
RUN composer global require squizlabs/php_codesniffer
RUN composer global require drupal/coder

# Set Drupal as default CodeSniffer Standard
RUN phpcs --config-set installed_paths /composer/vendor/drupal/coder/coder_sniffer/
RUN phpcs --config-set default_standard Drupal

WORKDIR /app

CMD ["phpcs"]
CMD ["phpcbf"]
